# Generated by Django 4.2.1 on 2023-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('country_name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=10)),
                ('address_1', models.CharField(max_length=1000)),
                ('address_2', models.CharField(max_length=1000)),
                ('email_address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('comments', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
